doc/userGuide.md

Update user guide for the ask-cli getting started section to correctly reflect the user flow. 

docs: update user guide for the ask-cli getting started section

---

README.md
package.json

Updated doc reference links in package.json and README
npm run tests success

docs: update doc reference links in package.json and README

---

README.md
doc/userGuide.md

* Moved "How does it work" to "Developing with Controls"
* Moved Controls source sections to "Contributing"
* Added "Purpose of Guide" section
* Updated content for "Prerequisites" and JS vs TS
Condensing start of guide so developers get to their first skill more quickly.

Update User Guide for First Skill Experience

---

doc/userGuide.md

- clean up some aspects of UserGuide.md (rephrase 'library control' -> 'built-in'), standardize column wrapping
- rewrite the interaction model section.
- add notes on how to author user guide content.
- The interaction model section was clunky.
- Formatting was inconsistent.

Improve 'interaction model' section of user guide (Mliddell/user guide)

---

package-lock.json
package.json
src/interactionModelGeneration/InteractionModelGenerator.ts
src/runtime/ControlHandler.ts

- Added userAgent information by default on ControlHandler to be added during skill building process using ask-sdk-controls library, the userAgent info is sent back as part of response to Alexa.
- Developers can also add additional userAgent if required by importing `UserAgentManager.registercomponent()` from ask-sdk-core.
- Added the pending PR: #2 with minor bug fixes.
- Bumped minor version of ask-sdk libraries.
- npm run release success.
- npm run build success.

Add userAgentInfo during skill building

---

src/controls/ControlManager.ts
src/controls/interfaces/IControlManager.ts
src/runtime/ControlHandler.ts
src/utils/SerializationValidator.ts

Improved the API of ControlManager.reestablishControlState and fix spurious failures.
A previous API change introduced ControlManager.reestablishControlStates with a default implementation that called ControlManager.loadControlStateMap.  This was not the right design as it conflated getting the state object with rebuilding a control tree from the state.  There was at least one concrete problem: if a developer implemented load/save to an external dataStore rather than SessionAttributes, we could cause additional loads from the DB during serialization-validation.  
Second commit is to fix spurious validation failures caused by JSON.stringify producing keys in different order. The fix is to do the equality testing on the objects via lodash isEquals rather than string-matching on the JSON.
no …

Fixes to SerializationValidator

---

src/controls/ControlManager.ts
src/controls/interfaces/IControlManager.ts
src/runtime/ControlHandler.ts

* Plumb async and await through `ControlManager.loadControlStateMap` and `ControlManager.saveControlStateMap`  and all call sites.
Custom implementations of `ControlManager.loadControlStateMap` and `ControlManager.saveControlStateMap` will likely need to use async.  Thus we need to plumb async and await to support this.
Manual testing.

feat: async load/save of control state

---

demo/QuestionnaireControl/src/index.ts
src/commonControls/ValueControl.ts
src/interactionModelGeneration/ControlInteractionModelGenerator.ts
test/commonControlTests/ValueControl.spec.ts

1. ValueControl was not producing a correct SlotElicitation Directive.  Thank you to @gabriellbdd for bringing this to my attention!
2. A second issue was identified during testing: ControlInteractionModelGenerator.ensureSlotIsDefined was being overly strict.
Closes #41 
tested before/after in live skill
unit test added.

fix(ValueControl): fix slot elicitation directive

---

tsconfig.json

referencing multiValueListControl and QuestionnaireControl in api_docs.

doc_: referencing multiValueListControl and QuestionnaireControl in docs

---

.commitlintrc.json
CHANGELOG.md

- refactored changelog
- change commitlint to use **docs** and **docs_**, since standard-version was not picking up doc and doc_ for autogeneration of Changelog doc section.

docs: fixed Changelog previous release messages and formatting issues

---

.gitattributes
.github/workflows/unit-test.yml
tsconfig.json

- Updated Github Action workflow to check for format checks, lints and build status on any open PRs
- Tested the Github Actions which executed on raising the PR [ref](https://github.com/alexa/ask-sdk-controls/actions/runs/497216154) 

Update Github Actions workflows

---

ide/vscode/launch.json
src/commonControls/DateControl.ts
src/commonControls/ValueControl.ts
src/commonControls/dateRangeControl/DateRangeControl.ts
src/commonControls/listControl/ListControl.ts
src/commonControls/multiValueListControl/MultiValueListControl.ts
src/commonControls/numberControl/NumberControl.ts
src/commonControls/questionnaireControl/QuestionnaireControl.ts
src/controls/ContainerControl.ts
src/controls/Control.ts
src/index.ts
src/utils/ControlUtils.ts
src/utils/InputUtil.ts
test/CustomSerdeTests.spec.ts
test/scenarios.spec.ts

- Control.value set to be mandatory in all controls
- changed DateRangeControl to use Control.value in its state to be consistent among all controls.
- standardized canHandle logic among all commonControl
- standardize lastInitiative state tracking on all controls
- npm run test success

Control Refactorings

---

src/commonControls/numberControl/NumberControl.ts

Fixed a bug with NumberControl and its use of slot elicitation.  
The change to use multi-value-slots introduced a bug that would manifest when the inputIntent was a Amazon_Number_ControlIntent and the output was an elicitation for the same.
The issue is that the MultiValueSlot feature introduces a new 'hidden' slot called __Conjunction and the ASK platform requires that a slot elicitation includes all slots (although it only tests this if the incoming intent matches the elicitation intent because of some internal limitations)
Note: unexpected slots are ok so this fix is safe even if we stop using MVS
Manual testing with demo/NumberControl.  To exercise the scenario, disable confirmation and reply to the question with an odd number so that validation fails.
```
A: what number
U: three
A: …
```

fix: NumberControl slot elicitation

---

demo/TwoLists/src/buildInteractionModel.ts
package-lock.json
src/commonControls/listControl/ListControl.ts
src/commonControls/questionnaireControl/QuestionnaireControl.ts
src/controls/DynamicContainerControl.ts
src/interactionModelGeneration/ControlInteractionModelGenerator.ts
src/interactionModelGeneration/InteractionModelGenerator.ts
src/runtime/ControlHandler.ts
src/utils/testSupport/SkillInvoker.ts
test/interactionModelGeneratorTests/interactionModelForTest.ts
test/interactionModelGeneratorTests/interactionModelGenerator.spec.ts

- Fixed issues occuring on executing `npm run build/rebuild` scripts on the framework due to recent release/update on `ask-smapi-models`
- npm run build success
- npm run release success

fix_: bug fixes to unblock build script to compile ts files

---

demo/TwoLists/src/buildInteractionModel.ts
src/utils/ControlUtils.ts
test/scenarios.spec.ts

This PR is fixes issues on TwoLists/buildInteractionModel.js script
Also, changed the behaviour on ControlUtils evaluateInputHandlers to throw an error when more than
one matching handlers are found.
This PR merges and fixes the comments and concerns raised on #65  and #61.
- npm run release success.

Fixes on buildInteractionModel and ControlUtils

---

package-lock.json
src/responseGeneration/ControlResponseBuilder.ts
src/runtime/ControlHandler.ts

Adding Directive support for RePrompt SPI
Fixed tsc, build issues caused from `Reprompt.OutputSpeech` made optional in [recent model updates](https://github.com/alexa/alexa-apis-for-nodejs/commit/6903d311a4c6195879014c5d05b0a4e0eac6f0ab#diff-577c69399a1023843312cff18c1a0440894f6fd08f513092669731c4fff4d19aL4626-L4628).
- npm run test success

feat: Adding Directive support for RePrompt SPI

---

package.json
src/commonControls/listControl/ListControl.ts
src/commonControls/multiValueListControl/MultiValueListControl.ts
src/commonControls/numberControl/NumberControl.ts
src/commonControls/questionnaireControl/QuestionnaireControl.ts
src/index.ts
src/modality/ModalityEvaluation.ts
src/runtime/ControlHandler.ts
src/utils/ResponseUtils.ts
test/commonControlTests/ListControl.spec.ts
test/commonControlTests/MultiValueListControl.spec.ts
test/commonControlTests/NumberControl.spec.ts
test/commonControlTests/QuestionnaireControl.spec.ts
test/modality.spec.ts
test/utilsTest/ResponseUtils.spec.ts

Correcting modality session behavior & touch event classification
These changes do the following:
- Export modality-related functions so that developers can use them as intended.
- Add VectorGraphic and EditText components as possible sources for touch events (instead of only TouchWrapper)
- Modifies behavior for default controls to instruct the device to enter an idle state when the recommended output modality is the screen, in order to not open the microphone.
- Modifies ControlHandler to still look for initiative candidates when the session state is set to IDLE (instead of only OPEN). This means initiative candidates will not be searched for unless the session state is END.
This change is a follow-up to [the previous commit introducing modality-related …

Correcting modality session behavior & touch event classification

---

src/responseGeneration/ControlResponseBuilder.ts

Just add missing method that is required to implement to ControlResponseBuilder class.
Add `addExperimentTrigger` method to the `ControlResponseBuilder` class. It's behavior is just calling same method of `coreBuilder` and return myself same as other methods defined in `ResponseBuilder`
When I run `npm install` and then `npm build` on my environment, find the following error.
```
$ tsc && npm run copyTestSupportFiles && npm run lint
src/responseGeneration/ControlResponseBuilder.ts:28:14 - error TS2420: Class 'ControlResponseBuilder' incorrectly implements interface 'ResponseBuilder'.
Property 'addExperimentTrigger' is missing in type 'ControlResponseBuilder' but required in type 'ResponseBuilder'.
28 export class ControlResponseBuilder implements ResponseBuilder {
~~~~~~~~~~~~~~~~~~~~~~ …
```

fix: Add addExperimentTrigger method to ControlResponseBuilder because ResponseBuilder require to implement it

---

src/commonControls/ValueControl.ts

The incorrect re-prompt is chosen in the ValueControl.
For example given a ValueControl with reprompt set for requestValue and requestChangedValue
```js
return new ValueControl({
id: 'userName',
slotType: 'LOGIN.name',
confirmationRequired: true,
validation: (state, input) =>
['Alexa', 'Amazon', 'Redfox'].includes(state.value!)
? true
: { renderedReason: 'Login name validation failed' },
prompts: {
requestValue: 'What is your login name?',
valueSet: '',
},
reprompts: {
requestValue: 'Please provide your login name',
requestChangedValue: 'What would you like to change your login name to?'
}
});
```
```
A: What is your login name?
U: <pauses long enough for reprompt to trigger>
A: Please provide your login name
```
```
A: What is your login name?
U: <pauses long enough for reprompt to …
```

fix: incorrect reprompt chosen based on act

---

.github/workflows/unit-test.yml
package-lock.json
package.json

- Update ask-sdk-core versions and fix vulnerabilities
- Fix Github Action workflows
- npm run test success

fix: update ask-sdk-core versions and fix vulnerabilities
